<?php
return array (
  'ZC_SITE_TURNOFF' => false,
  'ZC_DATABASE_TYPE' => 'pdo_mysql',
  'ZC_SQLITE_NAME' => '',
  'ZC_SQLITE_PRE' => 'zbp_',
  'ZC_MYSQL_SERVER' => 'localhost',
  'ZC_MYSQL_USERNAME' => 'gymsagac',
  'ZC_MYSQL_PASSWORD' => 'Sk35Ni1es3',
  'ZC_MYSQL_NAME' => 'gymsagac_blog',
  'ZC_MYSQL_CHARSET' => 'utf8',
  'ZC_MYSQL_PRE' => 'zbp_',
  'ZC_MYSQL_ENGINE' => 'MyISAM',
  'ZC_MYSQL_PORT' => '3306',
  'ZC_MYSQL_PERSISTENT' => false,
  'ZC_PGSQL_SERVER' => 'localhost',
  'ZC_PGSQL_USERNAME' => 'postgres',
  'ZC_PGSQL_PASSWORD' => '',
  'ZC_PGSQL_NAME' => '',
  'ZC_PGSQL_CHARSET' => 'utf8',
  'ZC_PGSQL_PRE' => 'zbp_',
  'ZC_PGSQL_PORT' => '5432',
  'ZC_PGSQL_PERSISTENT' => false,
  'ZC_YUN_SITE' => '',
)
?>